config/routes.rb
Taskrey::Application.routes.draw do
  

  get "statistics/show"
  get "statistics/details"
  
  resources :projects do 
    resources :project_users    
    get ':status', :to => "projects#show", :as => "task_status"
    get ':state', :to => "projects#show", :as => "task_status" 
    resources :tasks do
      resources :attachments
    end
  end
  
  devise_for :users

  get '/tasks/quick_search', :to => "tasks#quick_search"

  
  root :to => "projects#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  
  validates :estimated_time, numericality: { greater_than_or_equal_to: 1, only_integer: true }
  validates :completed_time, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  
  
  belongs_to :author, :class_name => "User", :foreign_key => "author_id" 
  belongs_to :assigned, :class_name => "User", :foreign_key => "assigned_to_id"
  has_many :attachments
  accepts_nested_attributes_for :attachments
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  
  def quick_search
    @s = Task.where('subject LIKE ?', "%"+params[:q]+"%")
    user_projects = current_user.projects.collect{|p| p.id }
    @output = ""
    @s.each do |s|
      if user_projects.include?(s.project_id)
        @output += "#{s.subject}|" + project_task_path(s.project_id, s) + "\n"
      end
    end
    render :text => @output
  end
  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @taskas = Task.find(params[:assigned_to_id])
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])
    @attachments = @task.attachments
    @attachment = Attachment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @project = Project.find(params[:project_id])
    @attachment = @task.attachments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @project = Project.find(params[:project_id])

  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(params[:task])
    @task.author_id = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(params[:project_id]), notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to project_task_path(params[:project_id],@task), notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_path(params[:project_id]) }
      format.json { head :ok }
    end
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
   # Returns an array of numbers options suitable for use in
  # a select helper.
  def estimated_time_options
    (1..8).collect do |numbers|
      [I18n.t('n numbers_et', :count => numbers), numbers]
    end
  end
  # Returns an array of numbers options suitable for use in
  # a select helper.
  def completed_time_options
    (0..8).collect do |numbers|
      [I18n.t('n numbers_ct', :count => numbers), numbers]
    end
  end
  
  # Returns an array of options suitable for use in
  # a select helper.
  def sequence_options
    (1..12).collect do |numb|
      [I18n.t('n sequence', :count => numb), numb]
    end
  end
  
  def diferencia(task)
    task.estimated_time - task.completed_time
  end
end

app/views/tasks/_attachment_field.erb
<div class="field">
    <%= f.label :attachment %><br />
    <%= f.file_field :attachment %>
  </div>

app/views/tasks/_form.html.erb
<!-- Agrego esras lineas para el calendarios -->

<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
		<script src="//code.jquery.com/jquery-1.10.2.js"></script>
		<script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
		<link rel="stylesheet" href="/resources/demos/style.css">
		<script>
			 $(function() {
					$( "#task_due_date" ).datepicker({ dateFormat: "yy-mm-dd" });
			});
		</script>
	</head>
	<body>		
	</body>
</html>

<%= form_for([Project.find(params[:project_id]), @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<table>
		<tr >
			<td colspan="10">
				<div class="form-group>
	  				<%= f.label :subject, class: 'col-md-3 control-label' %> 
	  				<div class="col-md-10">
	    				<%= f.text_area :subject, rows: 1, class: 'form-control' %>
	  				</div>
				</div>	
			</td>	
		</tr>
	
	  <tr>
	    <td colspan="4">
	    	<div class="form-group>
				<%= f.label :description, class: 'col-md-3 control-label' %>
			  	<div class="col-md-10">
			    	<%= f.text_area :description,rows: 2,  class: 'form-control' %>
			 	</div>
			</div>	
		</td>
	  </tr>
  
  <tr>
  		<th>
  			<div class="form-group>
	    		<%= f.label :state, class: 'col-md-2 control-label' %>
		    	<% states ={
		          'ACTIVA'=>1,
		          'CERRADA'=>2,
		          'OBSOLETA'=>3,
		          'CORTADA'=>4,
		          'EN PROGRESO'=>5,
		         } %>
		         
		         <div class="col-md-10">
				    <%= f.select :state,states %> </b>
				 </div>
			 </div>
  		</th>
  		<th>
	  		<div class="form-group>
	  			<%= f.label :estimated_time, class: 'col-md-2 control-label' %>
	  			<div class="col-md-10">
				    <%= f.select :estimated_time, estimated_time_options %>
				</div>
	  		</div>
  		</th>
  		<th>
  			<div class="form-group>
	  			<%= f.label :completed_time, class: 'col-md-2 control-label' %>
	  			<div class="col-md-10">
				    <%= f.select :completed_time, completed_time_options %>
				</div>
	  		</div>
  		</th>
  		<th>
  			<div class="form-group>
	  			<%= f.label :remaining_time, class: 'col-md-2 control-label' %>
	  			<div class="col-md-10">
				    <%= f.text_field :remaining_time %>
				</div>
	  		</div>
  		</th>

  </tr>
 	
  <tr>
	<td colspan="2">
    	<div class="form-group>
				<%= f.label :comentaries, class: 'col-md-3 control-label' %>
				  <div class="col-md-10">
				    <%= f.text_area :comentaries,rows: 2,  class: 'form-control' %>
				 </div>
			</div>	
	</td>		
	<td colspan="2">
  		<div class="form-group>
		  		<%= f.label :inpairments, class: 'col-md-3 control-label' %> 
		  			<div class="col-md-10">
		    			<%= f.text_area :inpairments, rows: 2, class: 'form-control' %>
		  			</div>
		</div>	
  	</td>
  </tr>
  
  <tr>
  	<th>
  		<div class="form-group>
	  		<%= f.label :due_date, class: 'col-md-3 control-label' %> 
	  			<div>
	    			<!--<%= f.date_select :due_date %>-->
	    			<%= f.text_field :due_date  %>  
	  			</div>
		</div>
  	</th>
  	<th>
  		<div class="form-group>
  			<%= f.label :complexity, class: 'col-md-3 control-label' %> 
  			<% complexities ={
	          'high'=>1,
	          'medium'=>2,
	          'low'=>3,
	          } %>
	  		
	  		<div class="col-md-10">
	    		<%= f.select :complexity,complexities %>
	  		</div>
		</div>
  	</th>
  	<th>
  		<div class="form-group>
	  		<%= f.label :assigned_to_id, class: 'col-md-3 control-label' %> 
	  			<div >
	    			<%= collection_select(:task, :assigned_to_id, User.all, :id, :email) %>
	  			</div>
		</div>
  	</th>
  	<th></th>
  </tr>
  
  <tr>
    <td colspan="2">
      <div class="actions">
        <%= f.submit controller.action_name.capitalize + " Task", :class => "btn primary" %>
      </div>
    </td>
  </tr>
</table>
<% end %>

app/views/tasks/edit.html.erb
<div  class="project_header">
<h2>
  <%=link_to @project.title, @project %>     
  &raquo; <%= link_to @task.subject, project_task_path(@project, @task) %> 
</h2>
</div>
<div class="clear"></div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th>Nombre</th>
    <th>WT</th>
    <th>WC</th>
    <th>WR</th>
    <th>Vence</th>
    <!--<th>Author</th>-->
    <th>Estado</th>
    <th>Asignada a</th>
    <th>Accion</th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
  	<% if task.assigned_to_id == current_user.id %>
    	<!--<td><%= link_to task.subject, project_task_path(@project, task) %></td>-->
    	<td><%= task.subject %></td>
    <%else%>
    	<td><%= link_to task.subject, project_task_path(@project, task) %></td>
    <%end%>
    <td><%= task.estimated_time %></td>
    <td><%= task.completed_time %></td>
    <td><%= diferencia(task) %></td>
    <td><%= task.due_date %></td>
    <td><%= task.state %></td>
    <!--<td><%= task.author.try(:email) %></td>-->
    <td><%= task.assigned.try(:email) %></td>
    <td><%= link_to 'Delete', project_task_path(@project, task), confirm: 'Are you sure?', method: :delete, :class => "btn inverse" %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tasks/new.html.erb
<div  class="project_header">
<h2>
  <%=link_to @project.title, @project %>     
  &raquo; New Task 
</h2>
</div>
<div class="clear"></div>
<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(params[:project_id]) %>

app/views/tasks/show.html.erb
<div  class="project_header">
<h2>
  <%=link_to @project.title, @project %>     
  &raquo; <%= @task.subject %> 
</h2>
<%= form_for [@project, @task] do |f| %>
  <%= link_to "Edit",  edit_project_task_path(@project, @task), :class => "btn primary btnsmall" %>
  <% if @task.closed == 1 %>
    <%= f.hidden_field :closed, :value => '0' %>
    <%= f.submit "Re-open", :class => "btn error" %>
  <% else %>
    <%= f.hidden_field :closed, :value => '1' %>
    <%= f.submit "Cerrar tarea", :class => "btn success" %> 
  <% end %>
<% end %>
</div>
<div class="clear"></div>

<table class="table table-striped">
  <tr>
    <td><b>Vence</b></td>
    <!--<td><b>Author</b></td>-->
    <td><b>Asignada a</b></td>
  </tr>
  <tr>
    <td><%= @task.due_date %></td>
    <!--<td><%= @task.author.email %></td>-->
    <td><%= @task.assigned.email %></td>
  </tr>
  <tr>
    <td colspan="3"><b>Descripcion de tarea</b></td>
  </tr>
  <tr>
    <td colspan="3"><pre class="prettyprint linenums"><%= raw BlueCloth.new(@task.description).to_html %></pre></td>
  </tr>
		<!--
	  <% if @attachments.size > 0 %>
	    <tr>
	      <td colspan="3"><b>Attachments:</b></td>
	    </tr>
	    <tr>
	      <td colspan="3">
	        <% @attachments.each do |a| %>
	          <div class="attachment">
	            <%=raw attachment_helper(a)%>
	            <%= link_to '[x]', project_task_attachment_path(@project, @task, a), confirm: 'Are you sure?', method: :delete %>
	          </div>
	          <div class="clear"></div>
	        <% end %>
	      </td>
	    </tr>
	  <% end %> 
	-->
  <!--
  <tr>
    <td colspan="3"><b>Add attachment:</b></td>
  </tr>
  -->
  <!--
  <tr>
    <td colspan="3">
      <%= render 'attachments/form' %>
    </td>
  </tr>
  -->
</p>