config/routes.rb
Taskrey::Application.routes.draw do
  

  get "statistics/show"
  get "statistics/details"
  
  resources :projects do 
    resources :project_users    
    get ':status', :to => "projects#show", :as => "task_status"
    get ':state', :to => "projects#show", :as => "task_status" 
    resources :tasks do
      resources :attachments
    end
  end
  
  devise_for :users

  get '/tasks/quick_search', :to => "tasks#quick_search"

  
  root :to => "projects#index"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :task
  mount_uploader :attachment, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:task_id])
    @attachment = @task.attachments.build(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to project_task_path(@project, @task), notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:task_id])
 
    @attachment = @task.attachments.find(params[:id])
    @attachment.destroy
    flash[:message] = "Attachment deleted."

    respond_to do |format|
      format.html { redirect_to project_task_path(@project, @task) }
      format.json { head :ok }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
  def attachment_helper(a)
    file_name = attachment_name(a)
    file_type = MIME::Types.type_for(file_name).join('/').split('/')[0]
    output = ''
    if file_type == "image"
      output << link_to(image_tag(a.attachment, {:size => "128x128"}) , a.attachment.to_s, :target => "_blank")
      output << attachment_name(a)
    else
      output << link_to(file_name, a.attachment.to_s, :target => "_blank")
    end
    output
  end

  def attachment_name(a)
    a.attachment.to_s.split('?')[0].split('/')[-1]
  end
end

app/views/attachments/_form.html.erb
<%= form_for([@project, @task, @attachment]) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.file_field :attachment %>
    <%= f.submit "Upload", :class => "btn success upload" %>
  
<% end %>

app/views/attachments/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= attachment.project_id %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @attachment.project_id %>
</p>


<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>