config/routes.rb
Taskrey::Application.routes.draw do
  

  get "statistics/show"
  get "statistics/details"
  
  resources :projects do 
    resources :project_users    
    get ':status', :to => "projects#show", :as => "task_status"
    get ':state', :to => "projects#show", :as => "task_status" 
    resources :tasks do
      resources :attachments
    end
  end
  
  devise_for :users

  get '/tasks/quick_search', :to => "tasks#quick_search"

  
  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :users, :through => :project_users
  has_many :project_users
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :verify_admin, :only => [:create, :destroy, :new, :edit]
  
  # GET /projects
  # GET /projects.json
  def index
    if current_user.admin == 1
      @projects = Project.all
    else
      @projects = current_user.projects
      if @projects.count == 1
        redirecting = 1
        redirect_to project_path(@projects.first)
      end
    end
    if redirecting.nil?
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @projects }
      end
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if current_user.admin == 1
      @project = Project.find(params[:id] || params[:project_id])
    else
      @project = current_user.projects.find(params[:id] || params[:project_id])
    end

    if params[:status] == "closed"
      @tasks = @project.tasks.order('id DESC').where(:closed => 1)
    else
      @tasks = @project.tasks.order('id DESC').where("closed IS NULL OR closed = 0")
    end
    @open = @project.tasks.order('id DESC').where("closed IS NULL OR closed = 0")
    @closed = @project.tasks.where(:closed => 1)
    
    if params[:status] == "activas"
      @tasks = @project.tasks.order('id DESC').where(:state => 1  ) # Estado Activo  aqui agregar para que ordene por secuence
    end
    if params[:status] == "cerradas"
      @tasks = @project.tasks.order('id DESC').where(:state => 2) # Estado Cerrada aqui agregar para que ordene por secuence
    end
    if params[:status] == "obsoleta"
      @tasks = @project.tasks.order('id DESC').where(:state => 3) # Estado Obsoleta aqui agregar para que ordene por secuence
    end
    if params[:status] == "cortada"
      @tasks = @project.tasks.order('id DESC').where(:state => 4) # Estado Cortada aqui agregar para que ordene por secuence
    end
    if params[:status] == "enprogreso"
      @tasks = @project.tasks.order('id DESC').where(:state => 5, :assigned_to_id => current_user.id) # Estado En progreso aqui agregar para que ordene por secuence
    end
    
    if params[:status] == "alta"
      @tasks = @project.tasks.order('id DESC').where(:complexity => 1, :assigned_to_id => current_user.id) 
    end
    
    if params[:status] == "media"
      @tasks = @project.tasks.order('id DESC').where(:complexity => 2, :assigned_to_id => current_user.id) 
    end
    
    if params[:status] == "baja"
      @tasks = @project.tasks.order('id DESC').where(:complexity => 3, :assigned_to_id => current_user.id) 
    end
    @todas = @project.tasks.where( :assigned_to_id => current_user.id)
    @activas = @project.tasks.where(:state=> 1)
    @cerradas = @project.tasks.where(:state => 2)
    @obsoleta = @project.tasks.where(:state => 3)
    @cortada = @project.tasks.where(:state => 4)
    @enprogreso = @project.tasks.where(:state => 5)
    
    @alta = @project.tasks.where(:complexity => 1)
    @media = @project.tasks.where(:complexity => 2)
    @baja = @project.tasks.where(:complexity => 3)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  # Returns an array of valid iteration length options suitable for use in
  # a select helper.
  def iteration_length_options
    (1..12).collect do |months|
      [I18n.t('n months', :count => months), months]
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
   
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  
  <div class="field">
    <%= f.label :iteration_length %><br />
    <%= f.select :iteration_length, iteration_length_options %>
  </div>
  
  <!--
  <div class="field">
    <%= f.label :private %><br />
    <%= f.number_field :private %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<div  class="project_header">
<h2>
  Projects 
</h2>
<%= link_to "New Project", new_project_path, :class => "btn primary" %>
</div>
<div class="clear"></div>
<table>
  <tr>
    <th>Project Name</th>
    <th>Start Date</th>
    <th>Iteration length</th>
    <th>Budget</th>
    <th> Tasks</th> <!-- Open tasks tareas abiertas-->
    <% if current_user.admin == 1 %>
      <th>Admin</th>
    <% end %>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.title, project %></td>
        <td><%= project.start_date %></td>
    <td><%= project.iteration_length %></td>
    <td><%= project.budget %></td>
    <td><%= project.tasks.where("closed IS NULL OR closed = 0").count %></td>
    <% if current_user.admin == 1 %>
      <td><%= link_to "Manage Users", project_project_users_path(project) %></td>
    <% end %>
	
  </tr>
<% end %>
</table>

<br />

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="project_header">
  <h1><%=link_to @project.title, @project %>
</h1>
<%= link_to "Nueva Tarea", new_project_task_path(@project), :class => "btn info" %> 
</div> 
	<div class="clear"></div> 
	<div class="project_nav">
		
		<%= link_to "Activas (#{@activas.size})", project_task_status_path(@project, 'activas'), :class => "btn danger" %>
		<%= link_to "Cerradas (#{@cerradas.size})", project_task_status_path(@project, 'cerradas'),:class => "btn success"  %>
		<%= link_to "Obsoletas (#{@obsoleta.size})", project_task_status_path(@project, 'obsoleta'),:class => "btn success" %>
		<%= link_to "Cortadas (#{@cortada.size})", project_task_status_path(@project, 'cortada'),:class => "btn success" %>
		<%= link_to "En progreso(#{@enprogreso.size})", project_task_status_path(@project, 'enprogreso'),:class => "btn primary" %>
		<%= link_to "Todas(#{@todas.size})", project_task_status_path(@project, 'todas'),:class => "btn inverse" %>
		
		
		<%= link_to "Alta(#{@alta.size})", project_task_status_path(@project, 'alta'),:class => "btn inverse" %>
		<%= link_to "Media(#{@media.size})", project_task_status_path(@project, 'media'),:class => "btn inverse" %>
		<%= link_to "Baja(#{@baja.size})", project_task_status_path(@project, 'baja'),:class => "btn inverse" %>
		<!--
		<%= link_to "Abiertas (#{@open.size})", project_task_status_path(@project, 'open') %>
		<%= link_to "Cerradas (#{@closed.size})", project_task_status_path(@project, 'closed') %>
		-->
</div>
<%= render :template => 'tasks/index' %>