config/routes.rb
Taskrey::Application.routes.draw do
  

  get "statistics/show"
  get "statistics/details"
  
  resources :projects do 
    resources :project_users    
    get ':status', :to => "projects#show", :as => "task_status"
    get ':state', :to => "projects#show", :as => "task_status" 
    resources :tasks do
      resources :attachments
    end
  end
  
  devise_for :users

  get '/tasks/quick_search', :to => "tasks#quick_search"

  
  root :to => "projects#index"

end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  before_filter :verify_admin
  def index
    @project = Project.find(params[:project_id])
    @project_user_list = @project.project_users    
    @project_users = ProjectUser.new
  end

  def create
    @project = Project.find(params[:project_id])
    @project_users = @project.project_users.create(params[:project_users])
    flash[:success] = "User was added to the project."
    redirect_to project_project_users_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @project_users = @project.project_users.find(params[:id]).destroy
    flash[:success] = "User was removed from the project."
    redirect_to project_project_users_path(@project)
  end

end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/views/project_users/create.html.erb
<h1>ProjectUsers#create</h1>
<p>Find me in app/views/project_users/create.html.erb</p>

app/views/project_users/destroy.html.erb
<h1>ProjectUsers#destroy</h1>
<p>Find me in app/views/project_users/destroy.html.erb</p>

app/views/project_users/index.html.erb
<div class="project_header">
  <h2><%= link_to @project.title, @project %> &raquo; Manage Users</h2>
</div>
<div class="clear"></div>

<%= form_for [@project, @project_users] do |f| %>
  <table class="noborder big_form">
    <tr>
      <td colspan="2"><b>Assigned To</b></td>
    </tr>
    <tr>
      <td colspan="2"><%= collection_select(:project_users, :user_id, User.all, :id, :email) %></td>
    </tr>
    <tr>
      <td><%= f.submit "Add User", :class => "btn success" %></td>
    </tr>
  </table>
<% end %>
<table class="noborder small_table">
  <thead>
    <th>User</th>
    <th>Action</th>
  </thead>
  <% @project_user_list.each do |pu| %>
    <tr>
      <td><%=pu.user.email%></td>
      <td><%=link_to "Delete", project_project_user_path(@project, pu), method: :delete, confirm: "Are you sure?", class: "btn error" %></td>
    </tr>
  <% end %>
</table>